name: Build and test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@6871f53176ad61624f978536bbf089c574dc19a2 # v8

      - name: Checkout project
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Cache Maven repository
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Setup Maven server settings
        uses: s4u/maven-settings-action@64e42c454dbd42ef6370ac8539685755aedd205b # v3.1.0
        with:
          servers: |
            [{
              "id": "nvd",
              "username": "john.doe",
              "password": "${{ secrets.NVD_KEY }}"
            }]

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Extract version from POM
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Upload SNAPSHOTs
        if: steps.branch-names.outputs.current_branch == 'main'
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2
        with:
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: false
          files: |
            target/dt-tool-*.*
